# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

#################################################################################
#                      OneBranch Pipelines - PR Build                           #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

# https://aka.ms/obpipelines/triggers
trigger:
  ## disable batching of changes when a push happens.
  batch: false
  branches:
    include:
    - main
    - release/*

pr:
- main
- release/*